### ISSUE TITLE
Incorrect bar code detection on Android

### ISSUE THREAD

**Issue by vishal423** [phonegap/phonegap-plugin-barcodescanner#153]
I am using Cyanogen 5.1.1 powered phone. When I try to use this cordova plugin in my mobile application, I get different result formats for same QR code. Every scan intermittently produces different output with following formats:
- UPC_E (every time different value is detected -- this should not be detected in first go)
- QR_CODE (whenever detected, produces correct output)

I see an enhancement to specify format to be detected. Till that's incorporated, can anyone guide on how to resolve this issue? 

Code snippet:
cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      }, 
      function (error) {
          alert("Scanning failed: " + error);
      }
   );

**Comment by epeleg** [comment]
Hi vishal423,
Where you able to resolve this?
We seem to have the same issue where we are trying to scan a QR and it ends up with a call to success but with a wrong value. Instead of an alpha numeric String that we know is encoded in the QR we get an 8 digits numeric value... 
unfortunately I don't have the result.format to even know if it did detect anther format (and which one) but I am guessing this is exactly what is happening.

**Comment by gabrielbma** [comment]
The exact same problem here, vishal423.

**Comment by epeleg** [comment]
@sarangan12 can you please explain why you closed this?

**Comment by sarangan12** [comment]
@epeleg Please refer the [issue](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/222). 

A major code change has been merged from Telerik branch to this branch. This has fixed majority of the iOS and Android bugs. But since the size of the merge is large, we cannot validate every issue and resolve it. So, I have closed all open issues related to android and ios. If you still find the issues, Please reopen the issue.

If you still find this issue is happening with the latest code, please reopen the issue.

**Comment by autodealers** [comment]
Today I tested the latest branch, but the issue with wrong UPC_E detection remains. Did somebody resolve the issue?

**Comment by fcafra** [comment]
this issue can be reopen please ?
I use phonegap-plugin-barcodescanner 6.0.5 for android 6 and sometime bar code detection on Android is not correct...

**Comment by mikepsinn** [comment]
I have this issue with Android incorrectly identifying a UPC_A (as identified correctly on iPhone) as a UPC_E with an incorrect value using v6.0.8.

Any suggestions?

Thanks!  :D
