### ISSUE TITLE
Unable to install plugin using Visual Studio 2015

### ISSUE THREAD

**Issue by jackita** [phonegap/phonegap-plugin-barcodescanner#157]
Hi everyone,

installing the version 4.1.0 using Visual Studio 2015 fails due some special xml character used in the plugin.xml file :
<framework src="src/windows/lib/WinRTBarcodeReader.csproj" custom="true" type="projectReference" versions="<=8.1"/>
If I replace '<' with '&lt;' in the 'versions' value all works fine.

**Comment by soerendalby** [comment]
If I understand you correctly, you have managed to fix this issue with Visual Studio 2015. Could you post the corrected plugin.xml version here? 

Thanks in advance.

**Comment by Mikey1982** [comment]
I have the same issue:
did you meant, if you replace '<' with xml escaped version ('&gt;') ?

**Comment by soerendalby** [comment]
Hi Mikey,  that was my interpretation and it worked. I have inlcuded my modifed version of plugin.xml here. Note that I renamed it to .xml.txt because xml is not a a supported file type here (?)


[plugin.xml.txt](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/105184/plugin.xml.txt)

**Comment by jackita** [comment]
Hi Mikey, I meant what you wrote, replace '<' with xml escaped version ('& l t ;' without spaces;))

**Comment by DigiBanks99** [comment]
This worked for me as well. Can we have this updated in the source?
