### ISSUE TITLE
Scan the Barcode within specific div instead of full screen

### ISSUE THREAD

**Issue by sivailangos** [phonegap/phonegap-plugin-barcodescanner#265]
How do we scan the QR code within particular div instead of Full Screen? Can we control the Scanning View port size?

**Comment by manuelprojects** [comment]
+1

**Comment by jcesarmobile** [comment]
Closing because it's a duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/223

On iOS and android it's impossible to put a native view inside a div, not sure about windows.
Making the scanner view not full screen might be possible, but will require a lot of extra work, PRs are welcomed
