### ISSUE TITLE
iOS: Camera is locked in portraitmode even when device is in landscape

### ISSUE THREAD

**Issue by vesters** [phonegap/phonegap-plugin-barcodescanner#40]
Seen on iPhone 5+6 and iPad 2. Others not tested.

On the iPad it seems about 30% of the screen is cut of (black). 

![img_3375](https://cloud.githubusercontent.com/assets/545257/8873990/9b3725d8-320c-11e5-9600-a541bb11c5f0.jpg)

**Comment by wildabeast** [comment]
I seem to recall discussing this a while ago, and it seemed that the community deemed that this was the desired behaviour. The reasoning was that if the scanner responded to orientation changes, then it would be impossible to scan vertical barcodes. That said perhaps this should be configurable instead of locked one way or the other?

The cut off screen on the iPad certainly seems like a bug though.

**Comment by vesters** [comment]
I think making it configurable would be very nice. 

I can see the problem with vertical codes - but especially when using the iPad on horizontal codes, it can seem more like a bug than a feature:-)

**Comment by derwaldgeist** [comment]
@Maintainer:

On native iOS, both issues can be fixed, and code scanning works fine even if device orientation is rotated. All you have to do, is to set the videoOrientation of the capture connection. And you have to take care of the varying frame bounds on screen rotation, which are the reason for the black border the OP mentioned.

Please have a look here:
http://stackoverflow.com/questions/15075300/avcapturevideopreviewlayer-orientation-need-landscape

If you're interested, I could send you a complete implementation I've just done in Swift. I just came here to see if I could save some time by using Phonegap instead of implementing scanning natively. :-)

**Comment by piersroberts** [comment]
@wildabeast is there any interest in completing this feature as a run-time switch and adding to other platforms? It'd be great to see this pulled in to the Phonegap build.

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it

**Comment by owq** [comment]
Issue seems to remain with c3bcd87.
However #171 fixes this.

**Comment by EddyVerbruggen** [comment]
Fixed in 5.0.1.
