### ISSUE TITLE
barcode scanner is not working in window8.1 metro apps

### ISSUE THREAD

**Issue by Sarajendran** [phonegap/phonegap-plugin-barcodescanner#42]
Environment Setup:-

Window 8.1
cordova 4.1.2 & 5.1.1
Issue description:-
I have create simple cordova windows8 application through below commands in command line prompt.
Cmd:-
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add windows
cordova plugin add https://github.com/hypery2k/cordova-barcodescanner-plugin.git

I have added new method called scan in index.js and added below code into it.
![image](https://cloud.githubusercontent.com/assets/13481014/8924718/00859618-351e-11e5-855e-6f7cbc87087f.png)

Also I have added button with click even mapping to scan method in index.js as shown below.
![image](https://cloud.githubusercontent.com/assets/13481014/8924722/1048c390-351e-11e5-9404-ea12ce2d8e76.png)

After creating the application I opened the project and created installable package AppPackage folder by following below link instructions of "To create an app package for local testing and distribution"
https://msdn.microsoft.com/en-us/library/hh975357.aspx

Now When I installed the application in windows surface. the application installed and opened. But when I click the scan button. The application behaves like below.
1. camera ui opened without scanning overlay/ square aniamtion.
2. I can see only cancel button. That too after clicking on the cancel it hangs.
3. Always opens front camera.
Expected Result:-
1. When we click scan button camera opens with scan overlay or animation.
2. There should be a button to switch cameras between front and back
3. Should have scan and cancel button.
4. On click of scan button should scam the barcode which is in infornt of the camera And on click of the cancel button should go back to the application

**Comment by VladyslavGoloshchapov** [comment]
I have same issue on tablet with Windows8.1 OS.

Also Preview looks kaleidoscoped (image attached).

![win_20150806_144537](https://cloud.githubusercontent.com/assets/1468675/9110887/22411e84-3c4a-11e5-8662-5ec33e716182.JPG)

**Comment by SunboX** [comment]
:+1:

**Comment by vladimir-kotikov** [comment]
@Sarajendran, the issue closed because most of the issues already addressed in master:
1. _camera opens with scan overlay or animation_ - this sounds more like a feature request, not a bug. There is more general ticket for this - #120
2. _There should be a button to switch cameras between front and back_ - again, this is a lack of feature, not a bug. Consider creating a separate issue, if you need this feature.
3. _Should have scan and cancel button_ - scan operation is performed periodically, so there is no need for separate "scan" button. Native-looking cancel button and cancelling on back button were added in 9dec84ced0050f7f7221bb49d0fad4f39ccb819b
4. _after clicking on the cancel it hangs_ - this was already fixed a long time ago. From initial description, looks like you are using hypery2k/cordova-barcodescanner-plugin, which is a fork of original repo and doesn't include latest bugfixes. Consider switching to this repo to get latest bugfixes for Windows platform.
