### ISSUE TITLE
variable CAMERA_USAGE_DESCRIPTION is not being used for iOS to generate NSCameraUsageDescription

### ISSUE THREAD

**Issue by adi1133** [phonegap/phonegap-plugin-barcodescanner#468]
The plugin variable `CAMERA_USAGE_DESCRIPTION` is not being used for iOS to generate `NSCameraUsageDescription` in the **Info.plist** file.

I have `CAMERA_USAGE_DESCRIPTION` set in both **package.json** and **config.xml**.
- cordova 7.0.1
- ios platform ios 4.4.0
- barcode scanner plugin version 6.0.6

**Comment by jcesarmobile** [comment]
Do you have other plugins installed that also use camera?

**Comment by adi1133** [comment]
I do not use any other plugins that access the camera. If this is difficult
to reproduce I will post a minimalistic project containing the bug.

**Comment by pom421** [comment]
I confirm the bug : 

In package.json :
```
            "phonegap-plugin-barcodescanner": {
                "CAMERA_USAGE_DESCRIPTION": " My Test xxx"
            },
```
In config.xml :
```
    <plugin name="phonegap-plugin-barcodescanner" spec="^6.0.6">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="My Test xxx" />
    </plugin>
```

In Info.plist : 
```
    <key>NSCameraUsageDescription</key>
    <string>This app requires camera access to function properly.</string>

```

- Cordova 7.0.1
- barcode-scanner 6.0.6

There are no other plugins in my app which use the camera.

**Comment by jcesarmobile** [comment]
So, how did you get the `This app requires camera access to function properly.` in the info.plist?

**Comment by pom421** [comment]
I assume it's arrived from scratch, after a blank cordova project generation.
I made no manual modification of my Info.plist file.
It looks like : 

```
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This app requires constant access to your location in order to track your position, even when the screen is off.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app requires access to your location when the screen is on and the app is displayed.</string>
    <key>NSCalendarsUsageDescription</key>
    <string>This app requires calendar access to function properly.</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>This app requires photo library access to function properly.</string>
    <key>NSBluetoothPeripheralUsageDescription</key>
    <string>This app requires bluetooth access to function properly.</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>This app requires microphone access to function properly.</string>
    <key>NSCameraUsageDescription</key>
    <string>This app requires camera access to function properly.</string>
    <key>NSMotionUsageDescription</key>
    <string>This app requires motion detection access to function properly.</string>
    <key>NSContactsUsageDescription</key>
    <string>This app requires contacts access to function properly.</string>
    <key>NSRemindersUsageDescription</key>
    <string>This app requires reminders access to function properly.</string>

```

**Comment by jcesarmobile** [comment]
No, cordova doesn't add any UsageDescription text, it has to be other of your plugins

**Comment by pom421** [comment]
You're right. This is due to cordova.plugins.diagnostic. Unfortunately, this 2 plugins was added to  work together, because diagnostic allows to easily manage permissions and barcode scanner needs camera permission.

Do you know if there is a mean to apply plugin's add in a deterministic way?

@ adi1133 : Be careful if you have a ios.json or fetch.json in plugins directory. If theses files exist, a cordova prepare will fetch metadata from them, not from package.json or config.xml. It was my case. I had to remove plugin one by one, remove platform ios and add it again to show a difference in Info.plist.  

I will close this bug anyway. Thanks for your responses.

**Comment by macdonst** [comment]
This is the same issue as reported in https://issues.apache.org/jira/browse/CB-12959

**Comment by jcesarmobile** [comment]
I think the problem adi1133 commented is https://issues.apache.org/jira/browse/CB-12041 (entries not added/restored), and the one pom421 commented is the one you link (conflict between plugins with the same usage descriptions).

Anyway, it's a cordova issue, closing this one.

**Comment by vousys** [comment]
First, this works for me with Cli-7.1.0 after apple reject me the ipa.

1) In your code, if you use for ex. cordova-plugin-barcodescanner and cordova-plugin-camera and cordova-plugin-ios-camera-permissions all the variables CAMERA_USAGE_DESCRIPTION, PHOTOLIBRARY_USAGE_DESCRIPTION should have the same string inside. If one of them is different apple rejects your ipa, because phonegap use the default variable .

ej:

<plugin name="cordova-plugin-ios-camera-permissions" >
     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
     <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
</plugin>

<plugin name="cordova-plugin-camera" > 
     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
     <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
<gap:plugin name="cordova-plugin-image-picker" source="npm" />
<gap:plugin name="cordova-plugin-base64-joewsh" source="npm" />   



<gap:plugin name="cordova-plugin-barcodescanner"   source="npm" spec="0.7.0" >

     <variable name="CAMERA_USAGE_DESCRIPTION" value="YOUR-PERMISSION-REQUEST" />
</gap:plugin>
2) add this code (remember to use the same string in the variables, as I mention before):

<platform name="ios">

     <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge" overwrite="true">
          <stringYOUR-PERMISSION-REQUEST</string>
     </edit-config>
     <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge" overwrite="true" >
          <string>YOUR-PERMISSION-REQUEST</string>
     </edit-config>
     <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge" overwrite="true">
          <string>YOUR-PERMISSION-REQUEST</string>
     </edit-config>
</platform>
