### ISSUE TITLE
QR code not recognised on iOS

### ISSUE THREAD

**Issue by luiza-cicone** [phonegap/phonegap-plugin-barcodescanner#513]
I have an app using the version 6.0.6 of the plugin, and cordova 6.5.0.

On iOS 10 (tested with an iPhone 6 and 5C), the scan doesn't recognise the following type of QR codes:
![screen shot 2017-07-25 at 14 29 10](https://user-images.githubusercontent.com/710939/28572071-ca2a20f0-7145-11e7-896f-e3e721ed15ce.png)
Previously, when using the version 5.0.0 it worked fine.

I think there is a similar issue #333 

Do you have new info on the issue? Do you know what could be the cause of the regression?

Thanks!

**Comment by macdonst** [comment]
@luiza-cicone does it recognize black on white QR codes okay?

**Comment by luiza-cicone** [comment]
I think it is more related to the size and contrast of the QR code and also maybe to the angle of scan.
I have this QR code printed on a device and it is a little bit smaller than in the image. I didn't have a problem scanning it before (with the previous app version integrating the v5.0.0 of the plugin) but now it takes some time before the QR code is recognised, by moving in different directions and angles. 
Also it's faster when scanning the same QR code rotated 90 degrees counterclockwise (not sure if it's related).

Do you have any idea what can be the cause? Thanks

**Comment by macdonst** [comment]
@luiza-cicone there seems to be some sort of a regression in ZXing, the library we depend on for barcode scanning between versions 5 and 6 of this plugin. I'm starting to think about alternative libraries to depend on for Android and iOS.

**Comment by andersborgabiro** [comment]
Angle shouldn't be a problem with QR codes. It's designed for it.

If you invert the given QR code to dark on light it works. That's how it should be. The contrast is also rather low.

My QR Code Generator complains when contrast is below 50% or inverted, as I know many readers have problems with that: http://qrcode.abiro.com/

You can alternatively use org.madmobile.cordovaplugins.zbarscanner. Not that I've found that it works better, but maybe different.

**Comment by jcesarmobile** [comment]
@luiza-cicone I've been able to scan that QR with an iPhone X with iOS 11.2.

@macdonst I don't think the plugin uses ZXing on iOS anymore, I've deleted all the ZXing code from `CDVBarcodeScanner.mm` class and it keeps working the same way. That's probably why there are a lot of complains about the plugin detection being worse than it used to be on version 3 of the plugin or earlier.

**Comment by andersborgabiro** [comment]
So it uses the builtin barcode scanning instead? https://developers.google.com/vision/android/barcodes-overview

**Comment by jcesarmobile** [comment]
@andersborgabiro talking about iOS, it uses `AVCaptureMetadataOutput` https://developer.apple.com/documentation/avfoundation/avcapturemetadataoutput

On Android I think it still uses ZXing

**Comment by andersborgabiro** [comment]
AVCaptureMetadataOutput is just for the image.

The plugin I use (6.0.7) still invokes zxing-all-in-one.h in CDVBarcodeScanner.mm.

**Comment by jcesarmobile** [comment]
Not going to downgrade to check, but on current master (version 7.0.0), despite `zxing-all-in-one.h` being included, it's not used anywhere, I did the check of removing the import and a few method declarations that had ZXing classes on it and the plugin didn't complain and continued working.

**Comment by happyi** [comment]
it recognition at android ,but didn't recognition at ios when the bar code have circular bead

**Comment by andersborgabiro** [comment]
I now use 7.0.2 on both Android and iOS, and it works well enough for my use cases.

From my experience:
- Always do dark on light (preferably black on white)
- Don't design the QR code: generate them with plain square modules
- Don't overlay images

Your creatives might care about design, but no one else does. When QR codes are made as per spec they are easier to recognize as QR codes, and easier to read.

**Comment by jpike88** [comment]
@andersborgabiro Honestly, you're not being helpful. "Well enough for your use cases" the use case that actually matters is what users decide, and users include the people who create said QR codes for consumption because the use case includes them. 

I've tested it against the built-in iOS 11 reader and also some free apps on the app store using the same QR codes, and our QR codes are perfectly 'to spec' including black on white. There is a serious gap in detection capabilities, whereas other scanners see the QR code instantly. So if the usability of this plugin is significantly worse than other QR scanners, that's simply not good enough.

As a side note, I'm pretty irked by your last comment. QR codes come in all shapes and sizes, and in a world where humans respond in different ways to visual stimuli, design is equally important to function. If everything was made 'to spec' as you put it, the world would be a very boring place.

More importantly, unless you intend on publishing your opinion to every 'creative' around the world and successfully get them to conform to it, this problem will persist anyway.

I'm going to fix it when I get a moment. I'll let this thread know when I have a solution.

**Comment by andersborgabiro** [comment]
It goes both ways. Sure, you can design QR codes so they barely work with scanners, but then they are of course not as useful. I give advice from that point of view.

I see way too many designed QR codes (because creatives think that's what users/customers can accept, which is a misunderstanding; admittedly they can look better, if that's a condition) that contain unnecessarily much information (either self-contained data or a very long URL, hence too much detail), with low contrast between dark and light, and are therefore almost impossible to read anyway.

Bad detection is very likely not specifically the fault of this plugin anyway, whether the detection is performed by an included software library like Zxing or by accessing platform features. Also, this is not the only barcode plugin available. Shop around.
