### ISSUE TITLE
Compatibility problem with barcodescanner.gradle

### ISSUE THREAD

**Issue by javenosa** [phonegap/phonegap-plugin-barcodescanner#569]
Hi,

I have a problem with the compatibility with this plugin and another one.
Can you change this version?

compile 'com.android.support:support-v4:+'

With a specific one? Like:
compile 'com.android.support:support-v4:25.3.1'

The barcode scanner always point to the latest version of this android dependency, so this make problem to retro compatibility with another's plugins with a specific version's.

Thanks

**Comment by macdonst** [comment]
Which is the other plugin you are having a problem with?

**Comment by shnist** [comment]
Because this plugin is generic with it's support it always fetches the latest version. 

Because of this I'm getting an error in my build because it's pulling down 26-alpha, where as most other plugins are more explicit in which version of support should be used. 

```
* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.
```

Changing `com.android.support:support-v4:+` to `com.android.support:support-v4:25.3.1` would alleviate this.

**Comment by maxwellnewage** [comment]
I have the same problem.
I need an official version without the + on dependency

**Comment by jcesarmobile** [comment]
It now can be configured, closing
