### ISSUE TITLE
Possibility to enable the shutter button on Android

### ISSUE THREAD

**Issue by sjoerdloeve** [phonegap/phonegap-plugin-barcodescanner#703]
On iOS it is possible to enable the shutter button and customize it via the interface builder. In the Android code I can not find traces of a shutter button. Is it possible to enable the shutter button on Android?

**Comment by speedfl** [comment]
+1

We can see that backbutton is closing the app for ionic and other cordova project because back event is populated

I see that issue: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/647 has been closed

Same here: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/584

Proposal has been made in https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/355

However if I use the camera plugin of cordova the back event just close the camera. So I am pretty sure we can do something.

But in any case just a back button could be appreciable

Regards

**Comment by jcesarmobile** [comment]
@speedfl I don't think shutter button and back button are the same

**Comment by sjoerdloeve** [comment]
@jcesarmobile @speedfl Correct, this issue is about a shutter button, not about the back button. 

On iOS i can set `USE_SHUTTER = 1` to show a shutter button. But for Android there is no option for this. With the shutter button you can first point to a barcode and then hit the shutter button to scan the barcode.

**Comment by speedfl** [comment]
Ah mea culpa :D
