### ISSUE TITLE
(iOS) After camera permission is denied tapping the camera shutter causes app to crash.

### ISSUE THREAD

**Issue by lfitzgerald** [phonegap/phonegap-plugin-barcodescanner#710]
### Expected Behaviour

When a user clicks "Don't Allow" on the camera permission dialog, any attempt to access the camera should throw an error that doesn't kill the app. 

### Actual Behaviour

When a user clicks "Don't Allow" on the permission dialog, tapping the camera shutter causes a fatal error that kills the app. 

#### Steps to Reproduce

https://github.com/lfitzgerald/phonegap-plugin-barcodescanner-crash/

Setup
- cordova platform add ios
- cordova build ios

1. Run project
2. Click the "Scan Barcode" button.
3. After the Camera viewfinder and Camera permission dialog load select the "Don't Allow" option.
4. Tap the Camera shutter icon.
5. At this point the app will go into the barcodeScanFailed method and the app will die.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10.3

#### Cordova CLI version and cordova platform version

8.0.0

 ios 4.5.5

#### Plugin version

   phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"

#### Sample Code that illustrates the problem

https://github.com/lfitzgerald/phonegap-plugin-barcodescanner-crash/

**Comment by sjoerdloeve** [comment]
I don't have this problem. Can you check if your *.plist file contains the `Privacy - Camera Usage Description` value with an explanation of why you want to use the camera? It's a required setting and will crash your app if empty or not present.

**Comment by lfitzgerald** [comment]
Yes if you look at the [config.xml ](https://github.com/lfitzgerald/phonegap-plugin-barcodescanner-crash/blob/master/config.xml) you'll see the NSCameraUsageDescription permission. When you add the platform that gets picked up in the main plist file. 

The app correctly prompts for permission. If the user grants permission it works as expected. If the user clicks "Don't Allow" it doesn't dismiss the camera. If the users touches the camera shutter it causes a fatal error that kills the app.

**Comment by soomdayer** [comment]
Late to the issue, but this is also broken in iOS for me (though it works just dandy on Android) 
(iOS 12.1.1, phonegap-plugin-barcodescanner 8.0.1)

To replicate (for me), 
- freshly reinstall my app
- click scan
- watch the barcode scanner overlay load in the background while iOS asks if it's allowed to use the camera
- then tell iOS, no, please don't let this app play with the camera (leaving the barcode scanning overlay up on the screen)
- click the camera icon in the lower right to "Take that picture"
- watch the app crash because it's not allowed to do that

It seems to be a difference in whether iOS has ever asked the user for permission before or not.  If the user sets the permission explicitly or has otherwise answered the permission question before (either allow or deny) the plugin works -- the failure handler is called and the scanner overlay is never actually displayed.  It's only when iOS doesn't know what the user is going to say and the plugin proceeds as if the answer will be "allow" that things go wrong.
