### ISSUE TITLE
After encoding Barcode in ios it not displayed  

### ISSUE THREAD

**Issue by Demokumar** [phonegap/phonegap-plugin-barcodescanner#712]
In ios platform, I use encode method to encode it give success alert but image, not displayed but in android platform it works

**Comment by sisPedro** [comment]
Im having the same problem. I have another app that uses barcodeScanner and it works fine. All I could find about this is that barcodeScanner succesfully creates the QRCode (haven't tried other code types) but returns 404. Strangely it says mime text/plain
![captura de pantalla 2018-11-12 a la s 16 31 02](https://user-images.githubusercontent.com/16280628/48370594-9724f800-e698-11e8-8e43-3a6f17f80378.png)

**Comment by dtgfranca** [comment]
I could resolve this problem this way. The function encode return an object with key, so I created my own modal page and I took this key and passed for my modal page

**Comment by ViCoastLLC** [comment]
cordova.plugins.barcodeScanner.encode(cordova.plugins.barcodeScanner.Encode.TEXT_TYPE, QRText,
                        function (success) {
}

This code shows barcode in android where it does not display anything in iOS app

**Comment by Story5** [comment]
It seems that the cordova-plugin-ionic-webview using WKWebView don't support the private file path like `/private/var/mobile/Containers/Data/Application/92D73642-D968-464E-8312-04BB724682D8/tmp/17BDC0C7-1A7D-4E2F-962B-8C78CBA4562C-5164-000004A04C6D1953.jpg`.

But the image path encoded by barcodescanner plugin is just a private path.

You can print the result and see the log below
```
{
"format":"TEXT_TYPE",
"file":"/private/var/mobile/Containers/Data/Application/861AC4C2-AF4C-46DF-943D-B1609DA7C35B/tmp/E670F14F-99E8-4BF5-9C1B-374778350384-5203-000004B0C8815B20.jpg"
}
```
After searching, I found 2 solutions.

One is to **downgrading to UIWebView**, the another is to **call `this.webview.convertFileSrc(your-file-path)` to fix your path**.

### 1. Downgrading to UIWebView
You can follow the ionic reference to downgrading to UIWebView

>[Downgrading to UIWebView](https://ionicframework.com/docs/wkwebview/#downgrading-to-uiwebview)

### 2.call `convertFileSrc()` to fix file path
You can follow the cordova-plugin-ionic-webview reference to fix file path

> [Migrating to 3.x](https://github.com/ionic-team/cordova-plugin-ionic-webview#migrating-to-3x)

your 'WebView' import code may like this, otherwise you may get a error "not found Webview"
```
import { WebView } from '@ionic-native/ionic-webview/ngx';
```

To be honest, I success to load image by downgrade to UIWebView, but failed to call `convertFileSrc` method.

When calling 'convertFileSrc' method, I got the error below and haven't figure out now.
> TypeError: Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordovaPropertyGet"]) is not a function. (In 'Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordovaPropertyGet"])(this, "convertFileSrc")', 'Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordovaPropertyGet"])' is an instance of Object)

**Comment by fafomx** [comment]
Hi, if I only want to generate QR code and save it in android and i dont want to show in QR image and continue with another code in my app. What i need to do?

**Comment by rioseco1** [comment]
> I could resolve this problem this way. The function encode return an object with key, so I created my own modal page and I took this key and passed for my modal page

@dtgfranca , I'm trying to implement your solution to the issue above.  Is the object's key called "file"?  I am trying to return the object with "return success" but I can't seem to get it right.  I was hoping you could share some insight into your solution.  Thanks!

**Comment by sisPedro** [comment]
@rioseco1 Please do not reply if your concern isn't directly tied to this issue. I would suggest you join [ionic slack](https://ionic-worldwide.slack.com/) or ask in the official Ionic forum.

**Comment by rioseco1** [comment]
@sisPedro, my concern is directly tied to the issue.   I run the barcodescanner plugin to encode but I am unable to display the generated QR Code in iOS.   I am breaking my head trying to resolve this. 

Could you tell me, after downgrading to UIWebView, when you encode in iOS, does the QR Code image open automatically as it does on Android?

Thanks!

**Comment by dtgfranca** [comment]
@rioseco1, I made thus:
```javascript
encodeQrCode(qrcode: string){
      this.scanner.encode( this.scanner.Encode.TEXT_TYPE, qrcode) 
      .then((data)=>{
          let modal =this.modalCtrl.create('ModalQrCodePage',{
                        qrcode: data.file
            })
            modal.present();
      }).
      catch(err =>{
            console.log(err);
      })
```

**Comment by rioseco1** [comment]
Thanks @dtgfranca .  I appreciate your response.
