### ISSUE TITLE
iOS: Camera does only work on app-restart

### ISSUE THREAD

**Issue by phoebusryan** [phonegap/phonegap-plugin-barcodescanner#810]
I just updatet the plugin to the newest version and the problem still exists.

See #733

Am I the only person with this memory issue?

Please help!

**Comment by bfabbri** [comment]
It's also happening to me! 

I'm trying to use the plugin in a Vuejs app.

The reader opens when the app goes to foreground..

**Comment by phoebusryan** [comment]
Thanks @bfabbri 

How can we fix that?

**Comment by bfabbri** [comment]
In my case, it seems to work properly if I put the scan method in plain javascript in a script tag and a button calling it the "traditional way". For example:



    function scan(){

      cordova.plugins.barcodeScanner.scan(function(result){

        //success callback
        alert(JSON.stringify(result));

      }, function(error) {

        //error callback
        alert(JSON.stringify(error));

      });
    }

    <button onclick="scan()">SCAN</button>


But, I'm not willing to do that because I want Vuejs to control all the frontend logic.

So, the answer for your question: I don't know how to fix it :(
I've tried a lot of different ways, but my best result was to open camera on app reopen.
I'll let you know if I find something that solves this..

But, for curiosity, as I'm in the beginning of my app dev, I'll try to use nativescript-vue (https://nativescript-vue.org/) and another barcode scanner plugin, specific to native script (https://www.npmjs.com/package/nativescript-barcodescanner).

**Comment by phoebusryan** [comment]
Man, I can't get it to work without app-restart. How is it possible that thousands of people use this plugin and no one cares about this issue?

@bfabbri Does the nativescript-barcodescanner work?

**Comment by phoebusryan** [comment]
@bfabbri your 'standalone-version' does not work in my case, either. hell. I really don't know why.

Whats the "Content-Security-Policy" you use? I mean the meta-tag.

**Comment by urkh** [comment]
I have the same error. I'm using this plugin with Vuejs. 

:cry:

**Comment by phoebusryan** [comment]
The problem is that iphones need a click to open the camera. There is no other way than the one @bfabbri provided above.

**Comment by urkh** [comment]
> The problem is that iphones need a click to open the camera. There is no other way than the one @bfabbri provided above.

Oh, thanks, let me try this

**Comment by bfabbri** [comment]
Hi @phoebusryan , we've migrated the app to React Native.. since I couldn't solve the issue with the camera open in vuejs, I didn't commit the tries, so I don't can't tell you now which Content-Security-Policy I was using when I was able to open the camera in my 'standalone-version'.. sorry :/
